title: Harry Bitten
logo:
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analytics & Other Projects 
  <br><br>
  Currently studying part-time for a Masters Degree in Big Data Science from Queen Mary University of London. Also working part-time as a Systems Support Analyst
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
