title: Harry Bitten
logo: "/images/HB.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analytics & Other Projects 
  <br><br>
  Keen Data Analyst with a Masters Degree from QMUL in Big Data Science. Currently working as an Associate at Itarle AG Algorithmic Trading Services
  <br><br>
  <a href="https://www.linkedin.com/in/harry-bitten-891305152/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
